apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-links
  labels:
    app: mongo-links
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-links
  template:
    metadata:
      labels:
        app: mongo-links
    spec:
      containers:
      - name: mongo-links
        image: 172.30.1.1:5000/nemo/mongo:latest
        ports:
        - containerPort: 27017
---
kind: Service
apiVersion: v1
metadata:
  name: mongo-links
spec:
  selector:
    app: mongo-links
  ports:
  - name: mongo
    port: 27017
    