apiVersion: apps/v1
kind: Deployment
metadata:
  name: tel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tel
  template:
    metadata:
      labels:
        app: tel
    spec:
      containers:
      - image: datawire/telepresence-k8s:0.93
        imagePullPolicy: IfNotPresent
        name: telepresence
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 25m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File