kind: Service
apiVersion: v1
metadata:
  name: feed
  lables:
    app: feed
spec:
  selector:
    app: feed
  ports:
  - name: http
    port: 80
    targetPort: 8080
  # - name: debug
  #   port: 8001
  #   targetPort: 8001