apiVersion: v1
kind: Template
metadata:
  name: likes-service
  annotations:
    description: "Nemo Likes service"
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: likes-${VERSION}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: likes
          version: ${VERSION}
      spec:
        containers:
        - name: likes
          image: 172.30.1.1:5000/nemo/likes:${IMAGE_TAG}
          env:
          - name: PROFILE
            value: PROD
          ports:
          - containerPort: 8080
parameters:
- description: App version
  name: VERSION
- description: Image tag
  name: IMAGE_TAG