kind: Service
apiVersion: v1
metadata:
  name: mongo-likes
spec:
  selector:
    app: mongo-likes
  ports:
  - name: mongo
    port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-likes
  labels:
    app: mongo-likes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-likes
  template:
    metadata:
      labels:
        app: mongo-likes
    spec:
      containers:
      - name: mongo-likes
        image: docker.io/mongo
        ports:
        - containerPort: 27017

