apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: likes
spec:
  host: likes
  subsets:
  - name: v0-10
    labels:
      version: v0-10
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: likes
spec:
  hosts:
    - likes
  http:
  - route:
    - destination:
        host: likes
        subset: v0-10
    # fault:
    #   delay:
    #     fixedDelay: 10s
    #     percent: 100
