apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: likes
spec:
  host: likes
  subsets:
  - name: v0-1
    labels:
      version: v0-1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: likes
spec:
  hosts:
    - likes
  http:
  - route:
    - destination:
        host: likes
        subset: v0-1

