apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: likes
spec:
  host: likes
  # trafficPolicy:
  #   connectionPool:
  #     http:
  #       http1MaxPendingRequests: 1
  #       maxRequestsPerConnection: 1
  #     tcp:
  #       maxConnections: 1
  #   outlierDetection:
  #     consecutiveErrors: 1
  #     interval: 1s
  #     baseEjectionTime: 3m
  #     maxEjectionPercent: 50
  subsets:
  - name: v0-10
    labels:
      version: v0-10
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: likes
spec:
  hosts:
    - likes
  http:
  - route:
    - destination:
        host: likes
        subset: v0-10
    # fault:
    #   delay:
    #     fixedDelay: 1s
    #     percent: 100
