apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tkit
  template:
    metadata:
      labels:
        app: tkit
    spec:
      containers:
      - name: tkit
        image: 172.30.1.1:5000/nemo/tkit:latest
        command: ["/bin/bash", "-c", "sleep 3600"]