apiVersion: v1
kind: Template
metadata:
  name: comments-service
  annotations:
    description: "Nemo Comments service"
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: comments-${VERSION}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: comments
          version: ${VERSION}
      spec:
        containers:
        - name: comments
          image: 172.30.1.1:5000/nemo/comments:${IMAGE_TAG}
          env:
          - name: MONGO_HOST
            value: mongo-comments
          ports:
          - containerPort: 8080
parameters:
- description: App version
  name: VERSION
- description: Image tag
  name: IMAGE_TAG