apiVersion: v1
kind: Template
metadata:
  name: feed-service-debug
  annotations:
    description: "Nemo Feed service"
objects:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: feed-${VERSION}-d
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: feed
            debug: ${VERSION}-d
            version: ${VERSION}-d
        spec:
          containers:
            - name: feed
              image: 172.30.1.1:5000/nemo/feed:${IMAGE_TAG}
              command:
                [
                  "/bin/bash",
                  "-c",
                  "java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8001,suspend=y -jar /app/feed-SNAPSHOT.jar"
                ]

              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: prod
              ports:
                - containerPort: 8001
parameters:
  - description: App version
    name: VERSION
  - description: Image tag
    name: IMAGE_TAG
