apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: feed-v0-10-d
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        annotations:
          sidecar.istio.io/status: '{"version":"48f39c4792663fa70ea9c6eb9c29612031cbe36a3850b41faa407da434ec11d3","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
        creationTimestamp: null
        labels:
          app: feed
          debug: feed-debug
          version: v0-10-d
      spec:
        containers:
        - command:
          - /bin/bash
          - -c
          - java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=*:5005,suspend=y
            -jar /app/feed-SNAPSHOT.jar
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          image: 172.30.1.1:5000/nemo/feed:0.10
          name: feed
          ports:
          - containerPort: 8080
          - containerPort: 5005
          resources: {}
        - args:
          - proxy
          - sidecar
          - --configPath
          - /etc/istio/proxy
          - --binaryPath
          - /usr/local/bin/envoy
          - --serviceCluster
          - feed
          - --drainDuration
          - 45s
          - --parentShutdownDuration
          - 1m0s
          - --discoveryAddress
          - istio-pilot.istio-system:15007
          - --discoveryRefreshDelay
          - 1s
          - --zipkinAddress
          - zipkin.istio-system:9411
          - --connectTimeout
          - 10s
          - --proxyAdminPort
          - "15000"
          - --controlPlaneAuthPolicy
          - NONE
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ISTIO_META_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ISTIO_META_INTERCEPTION_MODE
            value: REDIRECT
          - name: ISTIO_META_app
            value: feed
          - name: ISTIO_META_debug
            value: feed-debug
          - name: ISTIO_META_version
            value: v0-10-d
          image: docker.io/istio/proxyv2:1.0.3
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          ports:
          - containerPort: 15090
            name: http-envoy-prom
            protocol: TCP
          resources:
            requests:
              cpu: 10m
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1337
          volumeMounts:
          - mountPath: /etc/istio/proxy
            name: istio-envoy
          - mountPath: /etc/certs/
            name: istio-certs
            readOnly: true
        initContainers:
        - args:
          - -p
          - "15001"
          - -u
          - "1337"
          - -m
          - REDIRECT
          - -i
          - '*'
          - -x
          - ""
          - -b
          - 8080,5005
          - -d
          - ""
          image: docker.io/istio/proxy_init:1.0.3
          imagePullPolicy: IfNotPresent
          name: istio-init
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            privileged: true
        volumes:
        - emptyDir:
            medium: Memory
          name: istio-envoy
        - name: istio-certs
          secret:
            optional: true
            secretName: istio.default
  status: {}
kind: List
metadata: {}
---
