apiVersion: v1
kind: Template
metadata:
  name: links-service
  annotations:
    description: "Nemo Links service"
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: links-${VERSION}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: links
          version: ${VERSION}
      spec:
        containers:
        - name: links
          image: 172.30.1.1:5000/nemo/links:${IMAGE_TAG}
          env:
          - name: PROFILE
            value: PROD
          ports:
          - containerPort: 8080
parameters:
- description: App version
  name: VERSION
- description: Image tag
  name: IMAGE_TAG