apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: links
spec:
  host: links
  subsets:
  - name: v0-7
    labels:
      version: v0-7
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: links
spec:
  hosts:
    - links
  http:
  - route:
    - destination:
        host: links
        subset: v0-7

