apiVersion: v1
kind: Template
metadata:
  name: identity-service
  annotations:
    description: "Nemo Identity service"
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: identity-${VERSION}
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: identity
          version: ${VERSION}
      spec:
        containers:
        - name: identity
          image: 172.30.1.1:5000/nemo/identity:${IMAGE_TAG}
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          ports:
          - containerPort: 8080
parameters:
- description: App version
  name: VERSION
- description: Image tag
  name: IMAGE_TAG