kind: Service
apiVersion: v1
metadata:
  name: pg
spec:
  selector:
    app: pg
  ports:
  - name: pg
    port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  labels:
    app: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - name: pg
        image: docker.io/postgres
        ports:
        - containerPort: 5432
