apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: identity
spec:
  host: identity
  subsets:
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: identity
spec:
  hosts:
    - identity
  http:
  - route:
    - destination:
        host: identity
        subset: v2


