apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-11-03T14:21:12Z
  generation: 1
  labels:
    telepresence: 5caaaf27e48c4168bf0939f799e0122a
  name: telepresence-1541254870-407438-14548
  namespace: nemo
  resourceVersion: "21234"
  selfLink: /apis/extensions/v1beta1/namespaces/nemo/deployments/telepresence-1541254870-407438-14548
  uid: b74d70a7-df73-11e8-b38f-8c16458eff95
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      telepresence: 5caaaf27e48c4168bf0939f799e0122a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        telepresence: 5caaaf27e48c4168bf0939f799e0122a
    spec:
      containers:
      - image: datawire/telepresence-k8s:0.93
        imagePullPolicy: IfNotPresent
        name: telepresence-1541254870-407438-14548
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 25m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-11-03T14:21:14Z
    lastUpdateTime: 2018-11-03T14:21:14Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-11-03T14:21:12Z
    lastUpdateTime: 2018-11-03T14:21:14Z
    message: ReplicaSet "telepresence-1541254870-407438-14548-7b8f9bff56" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
